on: [push]
jobs:
  gen_iso:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-linux:latest-full-x86_64
      options: --privileged
    defaults:
      run:
        shell: sh
    steps:
      - name: Install dependencies for actions/checkout@v2
        run: xbps-install --yes -S gcc
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: Set repository for xbps
        run: |
          chmod +x ./ci/set_repository.sh
          ./ci/set_repository.sh
      - name: Install dependencies
        run: |
          chmod +x ./ci/install_dependencies.sh
          ./ci/install_dependencies.sh
      - name: Generate ISO
        run: |
          chmod +x ./gen.sh
          ./gen.sh
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: void-live-x86_64-${{ steps.date.outputs.date }}-${{ github.sha }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /root/void-mklive/void-live-x86_64-*.iso
          asset_name: void-live-x86_64-${{ steps.date.outputs.date }}-${{ github.sha }}.iso
          asset_content_type: application/gzip
